update pipelines

diff --git a/dockeragent/ubuntu/18.04/Dockerfile b/dockeragent/ubuntu/18.04/Dockerfile
--- a/dockeragent/ubuntu/18.04/Dockerfile
+++ b/dockeragent/ubuntu/18.04/Dockerfile
@@ -21,23 +21,23 @@ RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes \
                 libicu60 \
                 libunwind8 \
                 netcat \
-        && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
-        && apt-get install nodejs \
-        && echo "Node.js & npm version" \
-        && node -v && npm -v \
+        # && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
+        # && apt-get install nodejs \
+        # && echo "Node.js & npm version" \
+        # && node -v && npm -v \
 # set up nsswitch.conf for Go's "netgo" implementation (which Docker explicitly uses)
 # - https://github.com/docker/docker-ce/blob/v17.09.0-ce/components/engine/hack/make.sh#L149
 # - https://github.com/golang/go/blob/go1.9.1/src/net/conf.go#L194-L275
 # - docker run --rm debian:stretch grep '^hosts:' /etc/nsswitch.conf
-        && if [ ! -e /etc/nsswitch.conf ]; then echo 'hosts: files dns' > /etc/nsswitch.conf; fi \
-        && if ! curl -sL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${DOCKER_ARCH}/docker-${DOCKER_VERSION}.tgz" > docker.tgz; then \
-		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${DOCKER_ARCH}'"; \
-		exit 1; \
-	fi \
-	&& tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/ \
-	&& rm docker.tgz \
-        && echo "Docker version" \
-	&& docker --version \
+        # && if [ ! -e /etc/nsswitch.conf ]; then echo 'hosts: files dns' > /etc/nsswitch.conf; fi \
+        # && if ! curl -sL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${DOCKER_ARCH}/docker-${DOCKER_VERSION}.tgz" > docker.tgz; then \
+	# 	echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${DOCKER_ARCH}'"; \
+	# 	exit 1; \
+	# fi \
+	# && tar --extract --file docker.tgz --strip-components 1 --directory /usr/local/bin/ \
+	# && rm docker.tgz \
+        # && echo "Docker version" \
+	# && docker --version \
         && apt-get autoremove -y
 
 WORKDIR /azp
